apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-spring
  labels:
    app: forum-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-spring
  template:
    metadata:
      labels:
        app: forum-spring
    spec:
      containers:
        - name: forum-spring
          image: tatyana8/job4j_forum
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: forum-postgresdb-secret
                  key: postgres-username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forum-postgresdb-secret
                  key: postgres-password

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: forum-postgresdb-configmap
                  key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  selector:
    app: forum-spring
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32100

